### PR TITLE
remove seo for stealth discord

### PR DESCRIPTION
**Pull request by uhidontkno**
this is better to prevent against autoblocking

### CODE REVIEW

**Comment by IncognitoTGT** [comment]
Sodium's getting killed anyways in a few months so there really isn't a need
Ephemeral's meta tags only appear if it's a particular hostname

**Comment by uhidontkno** [comment]
sodium is a really good static proxy, it shouldn't be autoblocked.

**Review by IncognitoTGT — APPROVED** [review]
Merging
We're making a new one in react anyways (with all 100s in lighthouse :3)

**Comment by uhidontkno** [comment]
react belongs in my asscheeks

**Comment by IncognitoTGT** [comment]
It's a really fast proccy

**Pull request merged**
